const trip = [
  {
    trips: [
      {
        tripOriginCode: "MSP",
        tripDestinationCode: "FCO",
        tripOriginCity: "Minneapolis",
        tripDestinationCity: "Rome",
        layoverAirports: ["AMS"],
        tripStartDateTime: "2024-10-14T17:45:00",
        checkInLink: "https://www.klm.co.uk/check-in",
        segments: [
          {
            dateTime: "2024-10-14T17:45:00",
            airline: "KLM",
            flightNumber: 776,
            aircraftType: "Boeing 787-900",
            duration: "8h45m",
            origin: "MSP",
            destination: "AMS",
            originGate: "E9",
            destinationGate: "A47",
            originTerminal: "1",
            destinationTerminal: "C",
            onTimePrediction: "83",
            baggageClaim: "12",
            originAirporLatitude: "48.35378",
            originAirporLongitude: "11.78609",
            destinationAirporLatitude: "28.39878",
            destinationAirporLongitude: "9.76609",
            originTimeZoneOffset: "-06:00",
            destinationTimeZoneOffset: "+01:00",
            isDelayed: false,
          },
          {
            dateTime: "2024-10-15T10:20:00",
            airline: "ITA Airways",
            flightNumber: 441,
            aircraftType: "Airbus A321neo",
            duration: "2h10m",
            origin: "AMS",
            destination: "FCO",
            originGate: "H11",
            destinationGate: "C41",
            originTerminal: "3",
            destinationTerminal: "2",
            onTimePrediction: "94",
            baggageClaim: "9",
            originAirporLatitude: "48.35378",
            originAirporLongitude: "11.78609",
            destinationAirporLatitude: "28.39878",
            destinationAirporLongitude: "9.76609",
            originTimeZoneOffset: "+01:00",
            destinationTimeZoneOffset: "+01:00",
            isDelayed: true,
          },
        ],
      },

      {
        tripOriginCode: "JFK",
        tripDestinationCode: "LHR",
        tripOriginCity: "New York",
        tripDestinationCity: "London",
        layoverAirports: ["DUB"],
        tripStartDateTime: "2024-11-05T18:30:00",
        checkInLink: "https://webcheckin.aerlingus.com/html/checkIn/checkin.html",
        segments: [
          {
            dateTime: "2024-11-05T18:30:00",
            airline: "Aer Lingus",
            flightNumber: 1001,
            aircraftType: "Airbus A330-300",
            duration: "7h15m",
            origin: "JFK",
            destination: "DUB",
            originGate: "B25",
            destinationGate: "A5",
            originTerminal: "4",
            destinationTerminal: "2",
            onTimePrediction: "89",
            baggageClaim: "7",
            originAirporLatitude: "40.6413",
            originAirporLongitude: "-73.7781",
            destinationAirporLatitude: "53.4213",
            destinationAirporLongitude: "-6.2701",
            originTimeZoneOffset: "-05:00",
            destinationTimeZoneOffset: "+00:00",
            isDelayed: false,
          },
          {
            dateTime: "2024-11-06T08:00:00",
            airline: "British Airways",
            flightNumber: 548,
            aircraftType: "Airbus A320",
            duration: "1h30m",
            origin: "DUB",
            destination: "LHR",
            originGate: "B3",
            destinationGate: "C5",
            originTerminal: "1",
            destinationTerminal: "5",
            onTimePrediction: "92",
            baggageClaim: "4",
            originAirporLatitude: "53.4213",
            originAirporLongitude: "-6.2701",
            destinationAirporLatitude: "51.4700",
            destinationAirporLongitude: "-0.4543",
            originTimeZoneOffset: "+00:00",
            destinationTimeZoneOffset: "+00:00",
            isDelayed: false,
          },
        ],
      },
      {
        tripOriginCode: "SFO",
        tripDestinationCode: "HND",
        tripOriginCity: "San Francisco",
        tripDestinationCity: "Tokyo",
        layoverAirports: [],
        tripStartDateTime: "2024-12-15T12:15:00",
        checkInLink:
          "https://aswbe-i.ana.co.jp/international_asw/pages/webcheckin/checkin_search_input.xhtml?CONNECTION_KIND=JPN&LANG=en",
        segments: [
          {
            dateTime: "2024-12-15T12:15:00",
            airline: "ANA",
            flightNumber: 7,
            aircraftType: "Boeing 777-300ER",
            duration: "11h45m",
            origin: "SFO",
            destination: "HND",
            originGate: "F3",
            destinationGate: "D12",
            originTerminal: "I",
            destinationTerminal: "3",
            onTimePrediction: "91",
            baggageClaim: "18",
            originAirporLatitude: "37.6213",
            originAirporLongitude: "-122.3790",
            destinationAirporLatitude: "35.5494",
            destinationAirporLongitude: "139.7798",
            originTimeZoneOffset: "-08:00",
            destinationTimeZoneOffset: "+09:00",
            isDelayed: true,
          },
        ],
      },
    ],
  },
];

export default trip;
